### ISSUE TITLE
2.7.0 ?

### ISSUE THREAD

**Issue by Doormouse2House** [scijava/jython-shaded#3]
Hi Curtis, any reason why you never published your version-2.7.0 branch?  Wanted to test this with a project I'm working on.

Thanks

**Comment by ctrueden** [comment]
I didn't cut the release because we only get one chance—at least if we want the version numbers to stay in sync with upstream.

But you can definitely build it yourself and test it. If it works for you, we can cut the official release. How does that sound?

**Comment by ctrueden** [comment]
@Doormouse2House I finally did the update to 2.7.0. There were new dependencies which needed to be added to the shading. I [cut the 2.7.0 release](https://oss.sonatype.org/#nexus-search;gav~org.scijava~jython-shaded~2.7.0~~) just now—it should appear on Central shortly. Please give it a try and reply back if you find any issues.

**Comment by Doormouse2House** [comment]
@ctrueden Sorry just seen this now... We ended up moving away from this approach, hence my lack of response.  Thanks for getting back to me, regardless.
