### ISSUE TITLE
jython-standalone-shaded?

### ISSUE THREAD

**Issue by mslinn** [scijava/jython-shaded#6]
If I understand the docs correctly, this project is a repackaged version of the `jython` project. I would like a shaded version of `jython-standalone`. Alternatively, is there a combination of existing packages that accomplishes the same objective?

**Comment by ctrueden** [comment]
@mslinn This is a repackaged version of `jython-standalone`; see [here](https://github.com/scijava/jython-shaded/blob/jython-shaded-2.7.1/deps/pom.xml#L16). I did not create a shaded`org.python:jython` because it does not include the requisite Python code to make things work out of the box.

**Comment by ctrueden** [comment]
If you are having problems with the `os` module, note that you might have run into #5. Or if you are having some other issue, please feel free to describe in detail what goes wrong.

**Comment by mslinn** [comment]
Thanks for clarifying that this is the package that I need :)
